return {
    diagnostics = {
        BoldError = " ",
        Error = " ",
        BoldWarning = " ",
        Warning = " ",
        BoldInformation = "󰋼 ",
        Information = "󰋽 ",
        BoldQuestion = " ",
        Question = " ",
        BoldHint = "󰀨 ",
        Hint = "󰗖 ",
        Debug = " ",
        Trace = "✎ ",
    },
    startup = {
        sessions = "💻",
        findFiles = " ",
        findWord = " ",
        recentFiles = " ",
        fileBrowser = " ",
        colorschemes = " ",
        newFile = " ",
    },
}
